#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db_${CVAT_PORT}
    image: postgres:10.3-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis_${CVAT_PORT}
    image: redis:4.0.5-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    
    container_name: cvat_${CVAT_PORT}
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "${CVAT_PORT}:8080"
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        TF_ANNOTATION: "no"
        AUTO_SEGMENTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        WITH_TESTS: "no"
        TZ: "Etc/UTC"
        OPENVINO_TOOLKIT: "no"
    environment:
      ALLOWED_HOSTS: '*'
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      UI_PORT: ${UI_PORT}
      ANNOTATE_PATH: "${ANNOTATE_PATH}"
      PYTHONUNBUFFERED: 1
      SPLIT: ${SPLIT}
      CVAT_PORT: ${CVAT_PORT}  
      SEEN: ${SEEN}   
  
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models
      - /data/:/data/

  cvat_ui:
    container_name: cvat_ui_${CVAT_PORT}
    image: nginx
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui
    environment:
      REACT_APP_API_PROTOCOL: http
      REACT_APP_API_HOST: 13.235.205.188
      REACT_APP_API_PORT: 8080
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    ports:
      - "${UI_PORT}:80"

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:
